# Generated by Django 4.0.3 on 2022-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressMetroStation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("line_name", models.CharField(blank=True, max_length=200, null=True)),
                ("station_id", models.CharField(blank=True, max_length=200, null=True)),
                ("line_id", models.CharField(blank=True, max_length=200, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DriverLicenseType",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Error",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KeySkill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProfessionalRole",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "profarea_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "profarea_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkingDay",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingTimeInterval",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingTimeMode",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("premium", models.BooleanField(blank=True, null=True)),
                (
                    "billing_type_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "billing_type_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "response_letter_required",
                    models.BooleanField(blank=True, null=True),
                ),
                ("area_id", models.CharField(blank=True, max_length=200, null=True)),
                ("area_name", models.CharField(blank=True, max_length=200, null=True)),
                ("area_url", models.CharField(blank=True, max_length=200, null=True)),
                ("type_id", models.CharField(blank=True, max_length=200, null=True)),
                ("type_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_street",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_building",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address_lat", models.FloatField(blank=True, null=True)),
                ("address_lng", models.FloatField(blank=True, null=True)),
                (
                    "address_raw",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("allow_messages", models.BooleanField(blank=True, null=True)),
                ("site_id", models.CharField(blank=True, max_length=200, null=True)),
                ("site_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "experience_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "experience_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "schedule_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "schedule_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employment_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employment_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("accept_handicapped", models.BooleanField(blank=True, null=True)),
                ("accept_kids", models.BooleanField(blank=True, null=True)),
                ("archived", models.BooleanField(blank=True, null=True)),
                ("hidden", models.BooleanField(blank=True, null=True)),
                ("quick_responses_allowed", models.BooleanField(blank=True, null=True)),
                (
                    "accept_incomplete_resumes",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "employer_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_alternate_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_logo_urls_240",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_logo_urls_90",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_logo_urls_original",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "employer_vacancies_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("employer_trusted", models.BooleanField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "apply_alternate_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("has_test", models.BooleanField(blank=True, null=True)),
                (
                    "alternate_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("accept_temporary", models.BooleanField(blank=True, null=True)),
                ("salary_from", models.IntegerField(blank=True, null=True)),
                ("salary_to", models.IntegerField(blank=True, null=True)),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("salary_gross", models.BooleanField(blank=True, null=True)),
                (
                    "department_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_metro_station_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_metro_line_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_metro_station_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_metro_line_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("address_metro_lat", models.FloatField(blank=True, null=True)),
                ("address_metro_lng", models.FloatField(blank=True, null=True)),
                ("branded_description", models.TextField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                ("code", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "insider_interview_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "insider_interview_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vacancy_constructor_template_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "vacancy_constructor_template_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vacancy_constructor_template_top_picture_height",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "vacancy_constructor_template_top_picture_width",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "vacancy_constructor_template_top_picture_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vacancy_constructor_template_top_picture_blurred_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "address_metro_stations",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.addressmetrostation"
                    ),
                ),
                (
                    "driver_license_types",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.driverlicensetype"
                    ),
                ),
                (
                    "errors",
                    models.ManyToManyField(blank=True, null=True, to="hhru.error"),
                ),
                (
                    "key_skills",
                    models.ManyToManyField(blank=True, null=True, to="hhru.keyskill"),
                ),
                (
                    "professional_roles",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.professionalrole"
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.specialization"
                    ),
                ),
                (
                    "working_days",
                    models.ManyToManyField(blank=True, null=True, to="hhru.workingday"),
                ),
                (
                    "working_time_intervals",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.workingtimeinterval"
                    ),
                ),
                (
                    "working_time_modes",
                    models.ManyToManyField(
                        blank=True, null=True, to="hhru.workingtimemode"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancies",
            },
        ),
    ]
