# Generated by Django 4.0.3 on 2022-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hhru", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="response_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
